
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: iOS Unit Tests

on: workflow_dispatch

jobs:
  build:
    name: Xcode ${{ matrix.xcode }}
    strategy:
      matrix:
        xcode: ["14.0", "14.3.1", "latest-stable"]
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - uses: actions/checkout@v3

      - name: Create test configuration
        run: chmod +x ./build_configuration.sh && ./build_configuration.sh
        shell: bash

      - name: Build
        run: xcodebuild build -scheme SyntaxSparrow -configuration Debug -destination "platform=iOS"

      - name: Test
        run: xcodebuild test-without-building -scheme SyntaxSparrow -configuration Debug -destination "platform=iOS" -enableCodeCoverage YES